/* wording.js - generated by lotrodb/wording.py. Do not edit by hand.

   Every tooltip string the site prints, read out of the client's own
   StringTables (0x250001AF, 0x250001DA, 0x250001F9). Regenerate after a game
   patch; wording.py --check reports anything app.js still hardcodes.

   Use:  W("cooldown", secs(s.cooldown))   ->  "Cooldown: 30s"
         W("radius", fmt(r))               ->  "Radius: 10m"
         W("everySeconds", 1)              ->  "Every 1 second:"

   PASS VALUES ALREADY FORMATTED. The plural selector reads the PRINTED form,
   and String(4.0) is "4" in JavaScript - so W("healEveryFor", a, 4.0, 24)
   prints "every 4 seconds" where the client prints "every 4.0 seconds".
   Hand in fmt(iv, 1). This is why the data carries both [1] and [1.0].
*/
var WORDING = {
 "addsTo": {
  "parts": [
   "Adds ",
   " to ",
   ""
  ]
 },
 "adjustsAway": {
  "parts": [
   "Adjusts ",
   " ",
   " away from ",
   ""
  ]
 },
 "adjustsToward": {
  "parts": [
   "Adjusts ",
   " ",
   " towards ",
   ""
  ]
 },
 "any": {
  "parts": [
   "any"
  ]
 },
 "appliedEffects": {
  "parts": [
   "Applied Effects:"
  ]
 },
 "appliedToEnemies": {
  "parts": [
   "Effects applied to enemies within ",
   " metres: "
  ]
 },
 "appliedToFriends": {
  "parts": [
   "Effects applied to friends within ",
   " metres: "
  ]
 },
 "appliedToWithin": {
  "parts": [
   "Effects applied to ",
   " within ",
   " metres: "
  ]
 },
 "applyOnCrit": {
  "parts": [
   "Apply to target on critical:"
  ]
 },
 "applyOnCritOrDev": {
  "parts": [
   "Apply to target on Critical and Devastating Critical:"
  ]
 },
 "applyOnDevCrit": {
  "parts": [
   "Apply to target on devastating critical:"
  ]
 },
 "applyToAttacker": {
  "parts": [
   "Apply to the attacker:"
  ]
 },
 "applyToCaster": {
  "parts": [
   "Apply to the caster:"
  ]
 },
 "applyToSelf": {
  "parts": [
   "Apply to self:"
  ]
 },
 "applyToSource": {
  "parts": [
   "Apply to the source:"
  ]
 },
 "applyToTarget": {
  "parts": [
   "Apply to the target:"
  ]
 },
 "applyToTargets": {
  "parts": [
   "Apply to the target(s):"
  ]
 },
 "arc": {
  "parts": [
   "Arc (",
   " degrees with radius ",
   " metres)"
  ]
 },
 "areaShape": {
  "parts": [
   "Area-effect shape: "
  ]
 },
 "areaTargetLimit": {
  "parts": [
   "Area-effect target limit: "
  ]
 },
 "armourAmount": {
  "parts": [
   "",
   " Armour"
  ]
 },
 "armourStats": {
  "parts": [
   "Armour Stats:"
  ]
 },
 "armourValue": {
  "parts": [
   "Armour Value: "
  ]
 },
 "attunes": {
  "parts": [
   "Attunes: ",
   ""
  ]
 },
 "auraFellowship": {
  "parts": [
   "Aura - affects Fellowship members within ",
   " metres:"
  ]
 },
 "auraGroup": {
  "parts": [
   "Aura - affects Group members within ",
   " metres:"
  ]
 },
 "auraTargets": {
  "parts": [
   "Aura - affects targets within ",
   " metres:"
  ]
 },
 "bindAccountAcquire": {
  "parts": [
   "Bind to Account On Acquire"
  ]
 },
 "bindAccountEquip": {
  "parts": [
   "Bind to Account On Equip"
  ]
 },
 "bindOnAcquire": {
  "parts": [
   "Bind On Acquire"
  ]
 },
 "bindOnEquip": {
  "parts": [
   "Bind On Equip"
  ]
 },
 "box": {
  "parts": [
   "Box (",
   " metres long by ",
   " metres wide)"
  ]
 },
 "boxShape": {
  "parts": [
   "Box (",
   " metres long by ",
   " metres wide)"
  ]
 },
 "breakChanceDamage": {
  "parts": [
   "",
   "% break chance on damage"
  ]
 },
 "breakChanceHarm": {
  "parts": [
   "",
   "% break chance on harm"
  ]
 },
 "breakDamageAfter": {
  "parts": [
   "",
   "% break chance on damage after ",
   "s"
  ]
 },
 "breakHarmAfter": {
  "parts": [
   "",
   "% break chance on harm after ",
   "s"
  ]
 },
 "cannotBeDestroyed": {
  "parts": [
   "Cannot Be Destroyed"
  ]
 },
 "chanceTo": {
  "parts": [
   "",
   "% chance to"
  ]
 },
 "chanceToApply": {
  "parts": [
   "",
   "% chance to apply"
  ]
 },
 "chanceToX": {
  "parts": [
   "",
   "% chance to ",
   ""
  ]
 },
 "channelDuration": {
  "parts": [
   "Channel Duration: ",
   ""
  ]
 },
 "channelledSkill": {
  "parts": [
   "Channelled Skill"
  ]
 },
 "classColon": {
  "parts": [
   "Class: ",
   ""
  ]
 },
 "clearsAllGambits": {
  "parts": [
   "Clears All Gambits"
  ]
 },
 "comboStarter": {
  "parts": [
   "Combo Starter"
  ]
 },
 "consumedOnUse": {
  "parts": [
   "Consumed On Use"
  ]
 },
 "consumesAllRemaining": {
  "parts": [
   "Consumes all remaining ",
   ""
  ]
 },
 "cooldown": {
  "parts": [
   "Cooldown: ",
   ""
  ]
 },
 "cost": {
  "parts": [
   "Cost: ",
   " ",
   ""
  ]
 },
 "costPerSecond": {
  "parts": [
   "Cost: ",
   " ",
   " Per Second"
  ]
 },
 "damageEvery": {
  "parts": [
   "",
   " ",
   " Damage every #1:",
   " #1:{seconds|second[1]}."
  ]
 },
 "damageEveryFor": {
  "parts": [
   "",
   " ",
   " Damage every #1:",
   " #1:{seconds|second[1]} for #2:",
   " #2:{seconds|second[1]}."
  ]
 },
 "damageExpr": {
  "parts": [
   "Deals ",
   "-",
   " ",
   "",
   " (",
   "-",
   " base)"
  ]
 },
 "damageInitial": {
  "parts": [
   "",
   " ",
   " Damage initially."
  ]
 },
 "damageMitigation": {
  "parts": [
   "Damage Mitigation:"
  ]
 },
 "damageOne": {
  "parts": [
   "",
   " ",
   " Damage"
  ]
 },
 "damageRange": {
  "parts": [
   "",
   " - ",
   " ",
   " Damage"
  ]
 },
 "damageStats": {
  "parts": [
   "Damage Stats:"
  ]
 },
 "damageWord": {
  "parts": [
   "damage"
  ]
 },
 "disenchantsInto": {
  "parts": [
   "Disenchants into:"
  ]
 },
 "dispelAll": {
  "parts": [
   "Removes all ",
   " effects ",
   " from the target."
  ]
 },
 "dispelMaxStrength": {
  "parts": [
   "with maximum strength of ",
   ""
  ]
 },
 "dispelUpTo": {
  "parts": [
   "Removes up to #1:",
   " ",
   " #1:{effect[1]|effects} ",
   " from the target."
  ]
 },
 "dpsLine": {
  "parts": [
   "<rgb=#EEEE99>",
   " DPS</rgb>"
  ]
 },
 "drainEveryFor": {
  "parts": [
   "Drains ",
   " ",
   " every #1:",
   " #1:{seconds|second[1]} for #2:",
   " #2:{seconds|second[1]}."
  ]
 },
 "drainInitial": {
  "parts": [
   "Drains ",
   " ",
   " initially."
  ]
 },
 "drainOver": {
  "parts": [
   "Drains ",
   " ",
   " over #1:",
   " #1:{seconds|second[1]}."
  ]
 },
 "durability": {
  "parts": [
   "Durability ",
   "/",
   ""
  ]
 },
 "duration": {
  "parts": [
   "Duration: ",
   ""
  ]
 },
 "effectsOnRevival": {
  "parts": [
   "Effects to apply on revival:"
  ]
 },
 "everySeconds": {
  "parts": [
   "Every ",
   " {seconds|second[1]}:"
  ]
 },
 "expiresOutOfCombat": {
  "parts": [
   "Expires if out of combat for ",
   " {seconds|second[1]}."
  ]
 },
 "expiresOutOfCombatShort": {
  "parts": [
   "Expires if out of combat for a short amount of time."
  ]
 },
 "fastWith": {
  "parts": [
   "Fast\n",
   ""
  ]
 },
 "fellowshipStarter": {
  "parts": [
   "Fellowship Manoeuvre Starter"
  ]
 },
 "healEvery": {
  "parts": [
   "Heals ",
   " Morale every #1:",
   " #1:{seconds|second[1]}."
  ]
 },
 "healEveryFor": {
  "parts": [
   "Heals ",
   " Morale every #1:",
   " #1:{seconds|second[1]} for #2:",
   " #2:{seconds|second[1]}."
  ]
 },
 "healInitial": {
  "parts": [
   "Heals ",
   " Morale initially."
  ]
 },
 "immediateWith": {
  "parts": [
   "Immediate\n",
   ""
  ]
 },
 "induction": {
  "parts": [
   "Induction: ",
   ""
  ]
 },
 "itemLevel": {
  "parts": [
   "Item Level: ",
   ""
  ]
 },
 "itemLevelDown": {
  "parts": [
   "Item Level: <rgb=#B22222>",
   "</rgb> (",
   ")"
  ]
 },
 "itemLevelUp": {
  "parts": [
   "Item Level: <rgb=#00FF00>",
   "</rgb> (",
   ")"
  ]
 },
 "mainHand": {
  "parts": [
   "Main-hand"
  ]
 },
 "maxMoralePct": {
  "parts": [
   "",
   "% Maximum Morale"
  ]
 },
 "maxTargets": {
  "parts": [
   "Max Targets: ",
   ""
  ]
 },
 "maximumLevel": {
  "parts": [
   "Maximum Level ",
   ""
  ]
 },
 "minimumLevel": {
  "parts": [
   "Minimum Level: ",
   ""
  ]
 },
 "minusAmount": {
  "parts": [
   "-",
   " ",
   ""
  ]
 },
 "naturalWord": {
  "parts": [
   "Natural"
  ]
 },
 "negateDamage": {
  "parts": [
   "Negate ",
   " damage"
  ]
 },
 "offHand": {
  "parts": [
   "Off-hand"
  ]
 },
 "onApplication": {
  "parts": [
   "On application:"
  ]
 },
 "onEquip": {
  "parts": [
   "On Equip:"
  ]
 },
 "onExpiration": {
  "parts": [
   "<rgb=#990000>Applied on expiration:</rgb>"
  ]
 },
 "onExpirationInCombat": {
  "parts": [
   "<rgb=#990000>Applied on expiration if in combat:</rgb>"
  ]
 },
 "onRemoval": {
  "parts": [
   "<rgb=#990000>Applied on removal:</rgb>"
  ]
 },
 "onRemovalInCombat": {
  "parts": [
   "<rgb=#990000>Applied on removal if in combat:</rgb>"
  ]
 },
 "onUse": {
  "parts": [
   "On Use:"
  ]
 },
 "onWhat": {
  "parts": [
   "On ",
   ":"
  ]
 },
 "percentOf": {
  "parts": [
   "",
   "% of ",
   ""
  ]
 },
 "percentOfYour": {
  "parts": [
   "",
   "% of your ",
   ""
  ]
 },
 "pipDrainEvery": {
  "parts": [
   "Removes #1:",
   " #2:",
   " #1:{points|point[1]} every #3:",
   " #3:{seconds|second[1]}"
  ]
 },
 "pipGainEvery": {
  "parts": [
   "Adds #1:",
   " #2:",
   " #1:{points|point[1]} every #3:",
   " #3:{seconds|second[1]}"
  ]
 },
 "plusAmount": {
  "parts": [
   "+",
   " ",
   ""
  ]
 },
 "radius": {
  "parts": [
   "Radius: ",
   "m"
  ]
 },
 "range": {
  "parts": [
   "",
   "m Range"
  ]
 },
 "rangedHand": {
  "parts": [
   "Ranged"
  ]
 },
 "rank": {
  "parts": [
   "Rank: ",
   ""
  ]
 },
 "receiveEffect": {
  "parts": [
   "Receive effect:"
  ]
 },
 "reflectAmount": {
  "parts": [
   "Reflect ",
   " ",
   "damage"
  ]
 },
 "reflectEffect": {
  "parts": [
   "Reflect effect:"
  ]
 },
 "reflectFraction": {
  "parts": [
   "Reflect ",
   " of ",
   "damage"
  ]
 },
 "removesFrom": {
  "parts": [
   "Removes ",
   " from ",
   ""
  ]
 },
 "requiresAtLeast": {
  "parts": [
   "Requires at least ",
   " ",
   ""
  ]
 },
 "requiresAtMost": {
  "parts": [
   "Requires at most ",
   " ",
   ""
  ]
 },
 "requiresColon": {
  "parts": [
   "Requires: ",
   ""
  ]
 },
 "requiresGambit": {
  "parts": [
   "Requires an active gambit"
  ]
 },
 "requiresGloryRank": {
  "parts": [
   "Requires: Glory Rank ",
   ""
  ]
 },
 "resistance": {
  "parts": [
   "Resistance: ",
   ""
  ]
 },
 "resistanceWith": {
  "parts": [
   "Resistance: ",
   " (",
   ")"
  ]
 },
 "restoreEvery": {
  "parts": [
   "Restores ",
   " ",
   " every #1:",
   " #1:{seconds|second[1]}."
  ]
 },
 "restoreEveryFor": {
  "parts": [
   "Restores ",
   " ",
   " every #1:",
   " #1:{seconds|second[1]} for #2:",
   " #2:{seconds|second[1]}."
  ]
 },
 "restoreInitial": {
  "parts": [
   "Restores ",
   " ",
   " initially."
  ]
 },
 "restoresMaxOf": {
  "parts": [
   "Restores ",
   " of maximum ",
   ""
  ]
 },
 "returnOfDamage": {
  "parts": [
   "Return ",
   " of damage"
  ]
 },
 "reviveWith": {
  "parts": [
   "Target revives with ",
   "% ",
   ""
  ]
 },
 "selfOnCrit": {
  "parts": [
   "Applied to self on critical:"
  ]
 },
 "skillType": {
  "parts": [
   "Skill Type: ",
   ""
  ]
 },
 "socketType": {
  "parts": [
   "Socket Type: ",
   ""
  ]
 },
 "speedFast": {
  "parts": [
   "Fast"
  ]
 },
 "speedImmediate": {
  "parts": [
   "Immediate"
  ]
 },
 "sphere": {
  "parts": [
   "Sphere (",
   " metres radius)"
  ]
 },
 "sphereShape": {
  "parts": [
   "Sphere (",
   " metres radius)"
  ]
 },
 "startsFellowshipManoeuvre": {
  "parts": [
   "<rgb=#990000>Starts Fellowship Manoeuvre</rgb>"
  ]
 },
 "startsWarbandManoeuvre": {
  "parts": [
   "<rgb=#990000>Starts Warband Manoeuvre</rgb>"
  ]
 },
 "subtractsMaxOf": {
  "parts": [
   "Subtracts ",
   " of maximum ",
   ""
  ]
 },
 "tacticalWord": {
  "parts": [
   "Tactical"
  ]
 },
 "targetEffects": {
  "parts": [
   "Target Effects:"
  ]
 },
 "theFellowship": {
  "parts": [
   "the Fellowship"
  ]
 },
 "timesAmount": {
  "parts": [
   "x",
   " ",
   ""
  ]
 },
 "toMaster": {
  "parts": [
   "Applied to master while summoned:"
  ]
 },
 "toggleSkill": {
  "parts": [
   "Toggle Skill"
  ]
 },
 "unique": {
  "parts": [
   "Unique"
  ]
 },
 "userEffects": {
  "parts": [
   "User Effects:"
  ]
 },
 "value": {
  "parts": [
   "Value: ",
   " {coins|coin[1]}"
  ]
 },
 "whenBehind": {
  "parts": [
   "When behind a target:"
  ]
 },
 "whenInPosition": {
  "parts": [
   "When in Position:"
  ]
 },
 "worth": {
  "parts": [
   "Worth: "
  ]
 }
};

function W(key, /* ...values */) {
  var line = WORDING[key];
  var vals = Array.prototype.slice.call(arguments, 1);
  if (!line) return "";                      // never blank a tooltip over a key
  var parts = line.parts, bound = {}, out = [], keep = false, i;

  for (i = 0; i < parts.length; i++) if (parts[i].indexOf("{{keepspaces}}") >= 0) keep = true;
  /* A "#N:" tag binds selector N to the value in the slot that FOLLOWS the
     part it sits in - "every #1:_ #1:{seconds|second[1]} for #2:_ ..." binds
     1 to the interval and 2 to the span. Binding by position instead (N to
     the Nth value) read the amount as the interval and printed "for 1
     seconds." Mirrors render() in wording.py exactly. */
  for (i = 0; i < parts.length; i++) {
    var tagRe = /#(-?\d+):/g, tm;
    while ((tm = tagRe.exec(parts[i])) !== null) {
      var tn = parseInt(tm[1], 10), src = vals[i];
      if (tn === -1) {
        bound[-1] = (src && src.length !== undefined && typeof src !== "string") ? src.length : src;
      } else if (!(tn in bound)) {
        bound[tn] = src;
      }
    }
  }
  for (i = 0; i < vals.length; i++) {
    if (!((i + 1) in bound)) bound[i + 1] = vals[i];
  }

  /* The bracket matches the value's PRINTED form, not its number - the data
     carries both [1] and [1.0], and the client says "every 1.0 seconds". */
  function pick(options, count) {
    var opts = options.split("|"), dflt = null;
    var shown = (count === undefined || count === null) ? "" : String(count).trim();
    for (var j = 0; j < opts.length; j++) {
      var m = /^(.*?)\[([0-9.]+)\]$/.exec(opts[j]);
      if (m) { if (shown && shown === m[2]) return m[1]; }
      else dflt = opts[j];
    }
    return dflt === null ? opts[0] : dflt;
  }

  for (i = 0; i < parts.length; i++) {
    var text = parts[i].split("{{keepspaces}}").join("");
    text = text.replace(/\{([^{}]*\|[^{}]*)\}/g, function (whole, options, at) {
      var before = text.slice(0, at), tags = before.match(/#(-?\d+):/g), n;
      n = tags ? parseInt(tags[tags.length - 1].slice(1), 10) : (i || 1);
      return pick(options, bound[n]);
    });
    out.push(text.replace(/#(-?\d+):/g, ""));
    if (i < parts.length - 1) {
      var val = vals[i];
      if (val && val.length !== undefined && typeof val !== "string") val = Array.prototype.join.call(val, ", ");
      out.push(val === undefined || val === null ? "" : String(val));
    }
  }
  var s = out.join("");
  s = keep ? s : s.replace(/\s+/g, " ").replace(/\s+([.,;:!?])/g, "$1").trim();
  /* Some entries carry the client's colour inline - "<rgb=#990000>Applied on
     removal:</rgb>". Tooltip lines are placed with textContent and coloured by
     their CSS class, so the tags would show as literal text; strip them. The
     raw form is still in WORDING[key].parts for anything that wants it. */
  return s.replace(/<\/?rgb[^>]*>/g, "");
}

/* The client's own label for a line - the template's leading run, which is
   what tipLine wants in its .tk span. "Cooldown: _" -> "Cooldown:". */
function wLead(key) {
  var line = WORDING[key];
  if (!line || line.parts.length < 2) return null;
  var lead = line.parts[0].replace(/<\/?rgb[^>]*>/g, "").trim();
  return lead || null;
}

/* tipLine, worded by the client. The label comes from the template's leading
   run and the rest becomes the value, so the existing .tk / .tv styling holds
   and the English is the client's. */
function tipW(host, key, cls /*, ...values */) {
  var vals = Array.prototype.slice.call(arguments, 3);
  var whole = W.apply(null, [key].concat(vals));
  if (!whole) return;
  var lead = wLead(key);
  if (lead && whole.indexOf(lead) === 0) {
    tipLine(host, lead, whole.slice(lead.length).trim(), cls);
  } else {
    tipLine(host, null, whole, cls);
  }
}
